sudo: false
language: node_js
node_js:
  - 12.13.0 # use nodejs v12.13.0 LTS
cache: npm
branches:
  only:
    - dev # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: dev
  local-dir: public
  target_branch: master