sidebar_title: "Journal."
sidebar_subtitle: "隻言片語<br>於此匯聚"

truncate_len: 60

rss: atom.xml

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: 

gitment:
  enable: true
  mint: true
  count: true
  lazy: false
  cleanly: false
  language:
  github_user: moonipulate
  github_repo: moonipulate.github.io
  client_id: 44072973834b44150358
  client_secret: 5e55b3cca51738dc6875f14853d2e49b22acb53d
  proxy_gateway:
  redirect_protocol:

archives: true
